// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID   string `json:"id" dynamo:"ID,hash"`
	Text string `json:"text" dynamo:"text"`
	Done bool   `json:"done" dynamo:"done"`
	User *User  `json:"user" dynamo:"user"`
}

type User struct {
	ID   string `json:"id" dynamo:"ID,hash"`
	Name string `json:"name" dynamo:"name"`
}
